
// This file has been generated by the GUI designer. Do not modify.
namespace SmsApp
{
	public partial class ContactController
	{
		public virtual void Build ()
		{
			// Action group SmsApp.ContactController
		}
	}
}
